"""Distances

Revision ID: 39861eb771e8
Revises: b75c372fba3d
Create Date: 2016-07-23 12:45:11.289741

"""

# revision identifiers, used by Alembic.
revision = '39861eb771e8'
down_revision = 'b75c372fba3d'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('convention_location_distance',
    sa.Column('created_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True),
    sa.Column('updated_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('location_a_id', sa.BigInteger(), nullable=False),
    sa.Column('location_b_id', sa.BigInteger(), nullable=False),
    sa.Column('straight_line_distance', sa.Float(), nullable=True),
    sa.Column('driving_distance', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['location_a_id'], ['convention_location.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_b_id'], ['convention_location.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_convention_location_distance_created_at'), 'convention_location_distance', ['created_at'], unique=False)
    op.create_index(op.f('ix_convention_location_distance_updated_at'), 'convention_location_distance', ['updated_at'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_convention_location_distance_updated_at'), table_name='convention_location_distance')
    op.drop_index(op.f('ix_convention_location_distance_created_at'), table_name='convention_location_distance')
    op.drop_table('convention_location_distance')
    ### end Alembic commands ###
