"""Some items can be hidden

Revision ID: 8365ea7f66dd
Revises: 638a2f69d3ef
Create Date: 2016-09-12 22:50:52.764262

"""

# revision identifiers, used by Alembic.
revision = '8365ea7f66dd'
down_revision = '638a2f69d3ef'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('convention', sa.Column('is_hidden', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('convention_location', sa.Column('is_hidden', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('convention_theme', sa.Column('is_hidden', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('convention_type', sa.Column('is_hidden', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('convention_year', sa.Column('is_hidden', sa.Boolean(), server_default='0', nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('convention_year', 'is_hidden')
    op.drop_column('convention_type', 'is_hidden')
    op.drop_column('convention_theme', 'is_hidden')
    op.drop_column('convention_location', 'is_hidden')
    op.drop_column('convention', 'is_hidden')
    ### end Alembic commands ###
