"""Address field for locations

Revision ID: a0a0e47b8683
Revises: 39861eb771e8
Create Date: 2016-09-05 11:28:52.096295

"""

# revision identifiers, used by Alembic.
revision = 'a0a0e47b8683'
down_revision = '39861eb771e8'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('convention_location', sa.Column('address', sa.Unicode(length=256), nullable=True))
    op.create_index(op.f('ix_convention_location_address'), 'convention_location', ['address'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_convention_location_address'), table_name='convention_location')
    op.drop_column('convention_location', 'address')
    ### end Alembic commands ###
