"""Locations get lat/lon

Revision ID: b75c372fba3d
Revises: ec629bca38e7
Create Date: 2016-07-21 18:48:49.679913

"""

# revision identifiers, used by Alembic.
revision = 'b75c372fba3d'
down_revision = 'ec629bca38e7'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('convention_location', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('convention_location', sa.Column('longitude', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('convention_location', 'longitude')
    op.drop_column('convention_location', 'latitude')
    ### end Alembic commands ###
