"""Models

Revision ID: bf1e66e25fdb
Revises: None
Create Date: 2016-07-20 22:08:58.556323

"""

# revision identifiers, used by Alembic.
revision = 'bf1e66e25fdb'
down_revision = None

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('convention_location',
    sa.Column('created_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True),
    sa.Column('updated_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('country_code', sa.Unicode(length=6), nullable=False),
    sa.Column('state_province', sa.Unicode(length=128), nullable=False),
    sa.Column('city', sa.Unicode(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_convention_location_city'), 'convention_location', ['city'], unique=False)
    op.create_index(op.f('ix_convention_location_country_code'), 'convention_location', ['country_code'], unique=False)
    op.create_index(op.f('ix_convention_location_created_at'), 'convention_location', ['created_at'], unique=False)
    op.create_index(op.f('ix_convention_location_state_province'), 'convention_location', ['state_province'], unique=False)
    op.create_index(op.f('ix_convention_location_updated_at'), 'convention_location', ['updated_at'], unique=False)
    op.create_table('convention_theme_type',
    sa.Column('created_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True),
    sa.Column('updated_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Unicode(length=64), nullable=False),
    sa.Column('description', sa.UnicodeText(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_convention_theme_type_created_at'), 'convention_theme_type', ['created_at'], unique=False)
    op.create_index(op.f('ix_convention_theme_type_updated_at'), 'convention_theme_type', ['updated_at'], unique=False)
    op.create_table('convention_type',
    sa.Column('created_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True),
    sa.Column('updated_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Unicode(length=64), nullable=False),
    sa.Column('description', sa.UnicodeText(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_convention_type_created_at'), 'convention_type', ['created_at'], unique=False)
    op.create_index(op.f('ix_convention_type_updated_at'), 'convention_type', ['updated_at'], unique=False)
    op.create_table('convention',
    sa.Column('created_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True),
    sa.Column('updated_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('was_previously_id', sa.BigInteger(), nullable=True),
    sa.Column('contype_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Unicode(length=256), nullable=False),
    sa.Column('description', sa.UnicodeText(), nullable=True),
    sa.ForeignKeyConstraint(['contype_id'], ['convention_type.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['was_previously_id'], ['convention.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_convention_created_at'), 'convention', ['created_at'], unique=False)
    op.create_index(op.f('ix_convention_updated_at'), 'convention', ['updated_at'], unique=False)
    op.create_table('convention_theme',
    sa.Column('created_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True),
    sa.Column('updated_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('themetype_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Unicode(length=64), nullable=False),
    sa.Column('description', sa.UnicodeText(), nullable=True),
    sa.ForeignKeyConstraint(['themetype_id'], ['convention_theme_type.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_convention_theme_created_at'), 'convention_theme', ['created_at'], unique=False)
    op.create_index(op.f('ix_convention_theme_updated_at'), 'convention_theme', ['updated_at'], unique=False)
    op.create_table('convention_year',
    sa.Column('created_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True),
    sa.Column('updated_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('convention_id', sa.BigInteger(), nullable=False),
    sa.Column('theme_id', sa.BigInteger(), nullable=False),
    sa.Column('location_id', sa.BigInteger(), nullable=False),
    sa.Column('starts', sa.Date(), nullable=True),
    sa.Column('ends', sa.Date(), nullable=True),
    sa.Column('attendance', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['convention_id'], ['convention.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['convention_location.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['theme_id'], ['convention_theme.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_convention_year_created_at'), 'convention_year', ['created_at'], unique=False)
    op.create_index(op.f('ix_convention_year_updated_at'), 'convention_year', ['updated_at'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_convention_year_updated_at'), table_name='convention_year')
    op.drop_index(op.f('ix_convention_year_created_at'), table_name='convention_year')
    op.drop_table('convention_year')
    op.drop_index(op.f('ix_convention_theme_updated_at'), table_name='convention_theme')
    op.drop_index(op.f('ix_convention_theme_created_at'), table_name='convention_theme')
    op.drop_table('convention_theme')
    op.drop_index(op.f('ix_convention_updated_at'), table_name='convention')
    op.drop_index(op.f('ix_convention_created_at'), table_name='convention')
    op.drop_table('convention')
    op.drop_index(op.f('ix_convention_type_updated_at'), table_name='convention_type')
    op.drop_index(op.f('ix_convention_type_created_at'), table_name='convention_type')
    op.drop_table('convention_type')
    op.drop_index(op.f('ix_convention_theme_type_updated_at'), table_name='convention_theme_type')
    op.drop_index(op.f('ix_convention_theme_type_created_at'), table_name='convention_theme_type')
    op.drop_table('convention_theme_type')
    op.drop_index(op.f('ix_convention_location_updated_at'), table_name='convention_location')
    op.drop_index(op.f('ix_convention_location_state_province'), table_name='convention_location')
    op.drop_index(op.f('ix_convention_location_created_at'), table_name='convention_location')
    op.drop_index(op.f('ix_convention_location_country_code'), table_name='convention_location')
    op.drop_index(op.f('ix_convention_location_city'), table_name='convention_location')
    op.drop_table('convention_location')
    ### end Alembic commands ###
