"""Fix locations

Revision ID: de7543a566c3
Revises: bf1e66e25fdb
Create Date: 2016-07-20 22:10:09.069235

"""

# revision identifiers, used by Alembic.
revision = 'de7543a566c3'
down_revision = 'bf1e66e25fdb'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('convention_location', 'city',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.alter_column('convention_location', 'state_province',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('convention_location', 'state_province',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.alter_column('convention_location', 'city',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    ### end Alembic commands ###
