"""Remove theme type

Revision ID: ec629bca38e7
Revises: de7543a566c3
Create Date: 2016-07-21 17:59:53.271102

"""

# revision identifiers, used by Alembic.
revision = 'ec629bca38e7'
down_revision = 'de7543a566c3'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'convention_theme_ibfk_1', 'convention_theme', type_='foreignkey')
    op.drop_table('convention_theme_type')
    op.drop_column('convention_theme', 'themetype_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('convention_theme', sa.Column('themetype_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False))
    op.create_foreign_key(u'convention_theme_ibfk_1', 'convention_theme', 'convention_theme_type', ['themetype_id'], ['id'], onupdate=u'CASCADE', ondelete=u'CASCADE')
    op.create_table('convention_theme_type',
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('id', mysql.BIGINT(display_width=20), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
